<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Спецтехника</title>
</head>
<body>
<h1>Добро пожаловать на страницу!</h1>
<?php
 echo "Привет, $username!";
?>
<!--<button onclick="/get_cart">Открыть корзину</button>-->
<a href="/getCart" class="register-link">Корзина</a>
</body>
<a href="/logout" class="register-link">EXIT</a>
</html>
<div class="container">
    <h3>Каталог</h3>
    <div class="card-deck">
        <?php foreach ($products as $product): ?>
        <div class="card text-center">
            <a href="#">
                <div class="card-header">
                </div>
                <img class="card-img-top" src="<?php echo $product['photo'];?>" alt="Card image">
                <div class="card-body">
                    <p class="card-text text-muted">
                        <?php echo $product['name'];?>
                        <a href="#"><h5 class="card-title"><?php echo $product['description'];?></h5></a>
                    <div class="card-footer">
                        <?php echo $product['price'];?>
                    </div>
                    <form action="/addProduct" method="POST">
                        <input type="hidden" name="product_id" value="<?php echo $product['id'];?>">
                        <input type="number" name="quantity" value="1">
                        <input type="submit" value="Добавить в корзину">
                    </form>
                </div>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
</div>

<style>

    body {
        background-color: #f6f7f8;
    }

    /* основные стили */
    .profile {
        display: flex;
    }

    /* общие стили для всех кнопок авторизации, включая кнопки входа, корорые были на макете главной */
    .profile-button {
        background-color: #faf8f8;
        padding: 12px;
        font-size: 21px;
        line-height: 21px;
        text-decoration: none;
        color: #000;
        display: flex;
        align-items: center;
    }

    .profile-button:hover .profile-icon path{
        fill: #3d546f;
    }

    .profile-button:active {
        color: #c5c5c5;
    }

    .profile-button:active .profile-icon path{
        fill: #da1010;
    }

    /* стили отдельных элементов */
    .client-name {
        padding-left: 15px;
        padding-right: 10px;
    }

    .client-name .profile-icon {
        margin-right: 21px;
    }

    .profile-exit {
        padding-right: 10px;
        padding-left: 17px;
    }

    body {
        font-style: normal;
    }

    a {
        text-decoration: none;
        font-size: 23px;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
        text-align: center;
    }

    .card {
        float: left; /*Задаем обтекание*/
        margin-right: 20px;
        margin-left: 35px;


    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: gray;
        background-color: white;
    }

    .text-muted {
        font-size: 22px;
    }

    .card-footer{
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }

</style>